import logging
import time

from app.embedding_service import EmbeddingService
from app.vector_store import VectorStore
from app.llm_service import generate_rca
from app.jira_service import JiraService


# Configure logging once
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)


class RCAEngine:
    def __init__(self):
        logging.info("Initializing RCA Engine...")

        self.embedding_service = EmbeddingService()
        self.vector_store = VectorStore()
        self.jira_service = JiraService()

        logging.info("RCA Engine initialized successfully.")

    # ---------------------------------------------
    # Core RAG Pipeline
    # ---------------------------------------------
    def analyze_failure(self, new_log: str) -> str:
        """
        Full RAG pipeline:
        1. Generate embedding
        2. Search similar historical defects
        3. Call LLM for RCA generation
        """

        try:
            if not new_log or not new_log.strip():
                raise ValueError("Defect log cannot be empty.")

            start_time = time.time()

            logging.info("Step 1: Generating embedding...")
            embedding = self.embedding_service.generate_embedding(new_log)

            logging.info("Step 2: Searching similar defects...")
            similar_logs = self.vector_store.search_similar(embedding)

            logging.info(f"Retrieved {len(similar_logs)} similar logs.")

            logging.info("Step 3: Calling LLM for RCA...")
            rca_output = generate_rca(new_log, similar_logs)

            end_time = time.time()
            logging.info(
                f"RCA completed in {round(end_time - start_time, 2)} seconds."
            )

            return rca_output

        except Exception as e:
            logging.exception("RCA analysis failed.")
            raise e

    # ---------------------------------------------
    # RAG + Jira Integration
    # ---------------------------------------------
    def analyze_and_update_jira(self, issue_key: str, new_log: str) -> str:
        """
        Generates RCA and updates Jira:
        - Adds AI RCA comment
        - Adds label 'ai-rca'
        - Transitions issue to 'In Review'
        """

        try:
            if not issue_key or not issue_key.strip():
                raise ValueError("Issue key cannot be empty.")

            issue_key = issue_key.strip().upper()

            logging.info(f"Processing Jira issue: {issue_key}")

            # Generate RCA
            rca_output = self.analyze_failure(new_log)

            formatted_comment = f"""
🤖 AI Generated RCA:

{rca_output}

---
Generated by AI Defect RCA Assistant
"""

            # Update Jira
            logging.info("Updating Jira issue...")
            self.jira_service.add_comment(issue_key, formatted_comment)
            self.jira_service.add_label(issue_key, "ai-rca")
            self.jira_service.transition_issue(issue_key, "In Review")

            logging.info(f"Jira issue {issue_key} updated successfully.")

            return rca_output

        except Exception as e:
            logging.exception("Jira update failed.")
            raise e